# Web app (source repo still optional now)
app_repo: "https://github.com/Infratify/lab-final-project"
app_dir: "/opt/lab-final-project"

# ECR deploy (BONUS)
aws_region: "ap-southeast-1"
aws_account_id: "516267217090"
ecr_repo: "devops-bootcamp/final-project-syedazam"
app_image: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repo }}:latest"

app_container: "lab-final-project"

# Monitoring
monitoring_dir: "/opt/monitoring"
web_node_exporter_target: "10.0.0.5:9100"

# Grafana login
grafana_admin_user: "admin"
grafana_admin_password: "admin123"

# Cloudflare Tunnel (Monitoring)
cloudflared_hostname: "monitoring.syedazam.my"
cloudflared_origin_url: "http://127.0.0.1:3000"

# DO NOT COMMIT your real token here.
# Put it in ansible/group_vars/cloudflare_token.yml (ignored by git) OR pass via --extra-vars.
